### ISSUE TITLE
Прототип спрайт-анимации молнии

### ISSUE THREAD

**Issue by IDemiurge** [IDemiurge/Eidolons-Battlecraft#1]
Сделать прототип спрайт-анимации молнии, попробовать рандомизировать порядок, перекрасить текстуру, поиграть с размерами

**Comment by boblmarley** [comment]
Сделаем сегодня же )

**Comment by boblmarley** [comment]
кстати ) я нашёл фильтр для сглаживания самих текстур ))))

**Comment by IDemiurge** [comment]
Есть аккаунт на гитхабе?
